version: '3.0'
services:
  website:
    image: nginx:alpine
    ports:
      - "10000:80"
    volumes:
      - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/website
    depends_on:
      - api-server
    links:
      - api-server

  mobile-website:
    image: nginx:alpine
    ports:
      - "10001:80"
    volumes:
      - ./mobile/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mobile/dist:/website
    depends_on:
      - api-server
    links:
      - api-server
      
  api-server:
    build: ./api-server
    volumes:
      - /srv/cailab-homepage/db:/app/db
